data:
  domain_bounds: null
  mesh_file: usb_male.obj
  sampler_ratio: 0.3
  sampler_std: 0.05
  scale_factor: 1000
  test_batch_size: 10000
  test_resample_interval: -1
  test_samples: 100000
  train_batch_size: 100000
  train_resample_interval: -1
  train_samples: 10000000
loss:
  closest_point_weight: -1
  eikonal_weight: -1
  sdf_mse_weight: 1.0
model:
  activation_fn: swish
  domain_bounds:
  - - -9.380899999999999
    - 0.2129999999999992
    - -5.147
  - - 9.2419
    - 61.065
    - 5.053000000000001
  feature_size: 10
  interp_method: cubic2
  num_grid_points:
  - 5
  - 5
  - 5
  out_size: 1
  type: GridNet3D
  width_size: 100
train:
  learning_rate: 1e-3
  num_epochs: 2000
  plot_interval: 200
  save_interval: 100
